// GHIN screenshot imports live here after review in chat.
// Each imported round should use the same hole shape as app.js:
// Use round-level adjustedScore only when the GHIN card shows a different adjusted total.
// Hole shape: { hole, yards, strokeIndex, par, score, putts, gir, girMiss, fairway, penalties }
window.GHIN_IMPORTS = [
  {
    id: "ghin-2026-03-22-81h",
    label: "R1 – 18",
    date: "03/22/2026",
    course: "Wenatchee Golf & Country Club",
    tees: "Black/Blue",
    mode: "advanced",
    source: "ghin-screenshot",
    postedType: "H",
    crSlope: "70.3/133",
    pcc: "-",
    differential: 9.1,
    holes: [
      { hole: 1, yards: 537, strokeIndex: 13, par: 5, score: 6, putts: 2, gir: false, girMiss: "long", fairway: "hit", penalties: 0 },
      { hole: 2, yards: 149, strokeIndex: 17, par: 3, score: 4, putts: 2, gir: false, girMiss: "short", fairway: null, penalties: 0 },
      { hole: 3, yards: 389, strokeIndex: 3, par: 4, score: 5, putts: 2, gir: false, girMiss: "short", fairway: "right", penalties: 0 },
      { hole: 4, yards: 356, strokeIndex: 15, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "right", penalties: 0 },
      { hole: 5, yards: 356, strokeIndex: 5, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 6, yards: 193, strokeIndex: 11, par: 3, score: 3, putts: 1, gir: false, girMiss: "short", fairway: null, penalties: 0 },
      { hole: 7, yards: 550, strokeIndex: 9, par: 5, score: 5, putts: 2, gir: true, girMiss: null, fairway: "left", penalties: 0 },
      { hole: 8, yards: 397, strokeIndex: 1, par: 4, score: 4, putts: 1, gir: false, girMiss: "short", fairway: "hit", penalties: 0 },
      { hole: 9, yards: 356, strokeIndex: 7, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "right", penalties: 0 },
      { hole: 10, yards: 460, strokeIndex: 12, par: 5, score: 6, putts: 1, gir: false, girMiss: "left", fairway: "hit", penalties: 0 },
      { hole: 11, yards: 425, strokeIndex: 2, par: 4, score: 7, putts: 3, gir: false, girMiss: "short", fairway: "hit", penalties: 0 },
      { hole: 12, yards: 296, strokeIndex: 14, par: 4, score: 4, putts: 1, gir: false, girMiss: "short", fairway: "left", penalties: 0 },
      { hole: 13, yards: 498, strokeIndex: 10, par: 5, score: 6, putts: 2, gir: false, girMiss: "long", fairway: "right", penalties: 0 },
      { hole: 14, yards: 163, strokeIndex: 6, par: 3, score: 4, putts: 2, gir: false, girMiss: "short", fairway: null, penalties: 0 },
      { hole: 15, yards: 288, strokeIndex: 18, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "right", penalties: 0 },
      { hole: 16, yards: 362, strokeIndex: 4, par: 4, score: 4, putts: 1, gir: false, girMiss: "long", fairway: "hit", penalties: 0 },
      { hole: 17, yards: 131, strokeIndex: 16, par: 3, score: 3, putts: 2, gir: true, girMiss: null, fairway: null, penalties: 0 },
      { hole: 18, yards: 331, strokeIndex: 8, par: 4, score: 4, putts: 1, gir: false, girMiss: "short", fairway: "short", penalties: 0 },
    ],
  },
  {
    id: "ghin-2026-03-24-82a",
    label: "R2 – 18",
    date: "03/24/2026",
    course: "Rock Island Golf Course",
    tees: "Standard",
    mode: "advanced",
    source: "ghin-screenshot",
    postedType: "A",
    crSlope: "71.6/124",
    pcc: "-",
    differential: 9.5,
    holes: [
      { hole: 1, yards: 348, strokeIndex: 9, par: 4, score: 3, putts: 0, gir: false, girMiss: "short", fairway: "hit", penalties: 0 },
      { hole: 2, yards: 426, strokeIndex: 5, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 3, yards: 160, strokeIndex: 17, par: 3, score: 3, putts: 1, gir: false, girMiss: "short", fairway: null, penalties: 0 },
      { hole: 4, yards: 407, strokeIndex: 15, par: 4, score: 6, putts: 2, gir: false, girMiss: "short", fairway: "right", penalties: 0 },
      { hole: 5, yards: 570, strokeIndex: 7, par: 5, score: 6, putts: 3, gir: true, girMiss: null, fairway: "right", penalties: 0 },
      { hole: 6, yards: 403, strokeIndex: 3, par: 4, score: 3, putts: 0, gir: false, girMiss: "right", fairway: "hit", penalties: 0 },
      { hole: 7, yards: 195, strokeIndex: 13, par: 3, score: 4, putts: 2, gir: false, girMiss: "right", fairway: null, penalties: 0 },
      { hole: 8, yards: 532, strokeIndex: 1, par: 5, score: 7, putts: 2, gir: false, girMiss: "right", fairway: "right", penalties: 0 },
      { hole: 9, yards: 312, strokeIndex: 11, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 10, yards: 380, strokeIndex: 4, par: 4, score: 5, putts: 2, gir: false, girMiss: "right", fairway: "right", penalties: 0 },
      { hole: 11, yards: 320, strokeIndex: 14, par: 4, score: 4, putts: 0, gir: false, girMiss: "short", fairway: "left", penalties: 0 },
      { hole: 12, yards: 544, strokeIndex: 2, par: 5, score: 8, putts: 3, gir: false, girMiss: "short", fairway: "left", penalties: 0 },
      { hole: 13, yards: 357, strokeIndex: 12, par: 4, score: 6, putts: 2, gir: false, girMiss: "right", fairway: "hit", penalties: 0 },
      { hole: 14, yards: 187, strokeIndex: 16, par: 3, score: 3, putts: 2, gir: true, girMiss: null, fairway: null, penalties: 0 },
      { hole: 15, yards: 491, strokeIndex: 8, par: 5, score: 4, putts: 2, gir: true, girMiss: null, fairway: "right", penalties: 0 },
      { hole: 16, yards: 418, strokeIndex: 6, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "left", penalties: 0 },
      { hole: 17, yards: 411, strokeIndex: 10, par: 4, score: 5, putts: 2, gir: false, girMiss: "short", fairway: "short", penalties: 0 },
      { hole: 18, yards: 176, strokeIndex: 18, par: 3, score: 3, putts: 1, gir: false, girMiss: "long", fairway: null, penalties: 0 },
    ],
  },
  {
    id: "ghin-2026-03-26-41n",
    label: "R3 – F9",
    date: "03/26/2026",
    course: "Wenatchee Golf & Country Club",
    tees: "Black/Blue",
    mode: "advanced",
    source: "ghin-screenshot",
    postedType: "N",
    crSlope: "36.1/135",
    pcc: "-",
    differential: 7.7,
    holes: [
      { hole: 1, yards: 537, strokeIndex: 13, par: 5, score: 5, putts: 1, gir: false, girMiss: "long", fairway: "hit", penalties: 0 },
      { hole: 2, yards: 149, strokeIndex: 17, par: 3, score: 3, putts: 1, gir: false, girMiss: "left", fairway: null, penalties: 0 },
      { hole: 3, yards: 389, strokeIndex: 3, par: 4, score: 4, putts: 1, gir: false, girMiss: "long", fairway: "left", penalties: 0 },
      { hole: 4, yards: 356, strokeIndex: 15, par: 4, score: 5, putts: 3, gir: true, girMiss: null, fairway: "right", penalties: 0 },
      { hole: 5, yards: 356, strokeIndex: 5, par: 4, score: 4, putts: 1, gir: false, girMiss: "right", fairway: "left", penalties: 0 },
      { hole: 6, yards: 193, strokeIndex: 11, par: 3, score: 4, putts: 3, gir: true, girMiss: null, fairway: null, penalties: 0 },
      { hole: 7, yards: 550, strokeIndex: 9, par: 5, score: 6, putts: 2, gir: false, girMiss: "short", fairway: "right", penalties: 0 },
      { hole: 8, yards: 397, strokeIndex: 1, par: 4, score: 4, putts: 1, gir: false, girMiss: "long", fairway: "hit", penalties: 0 },
      { hole: 9, yards: 356, strokeIndex: 7, par: 4, score: 6, putts: 1, gir: false, girMiss: "long", fairway: "left", penalties: 0 },
    ],
  },
  {
    id: "ghin-2026-03-27-41n",
    label: "R4 – B9",
    date: "03/27/2026",
    course: "Wenatchee Golf & Country Club",
    tees: "Black/Blue",
    mode: "advanced",
    source: "ghin-screenshot",
    postedType: "N",
    crSlope: "34.2/131",
    pcc: "-",
    differential: 9.5,
    holes: [
      { hole: 10, yards: 460, strokeIndex: 12, par: 5, score: 5, putts: 1, gir: false, girMiss: "short", fairway: "right", penalties: 0 },
      { hole: 11, yards: 425, strokeIndex: 2, par: 4, score: 5, putts: 2, gir: false, girMiss: "short", fairway: "left", penalties: 0 },
      { hole: 12, yards: 296, strokeIndex: 14, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "left", penalties: 0 },
      { hole: 13, yards: 498, strokeIndex: 10, par: 5, score: 6, putts: 3, gir: true, girMiss: null, fairway: "right", penalties: 0 },
      { hole: 14, yards: 163, strokeIndex: 6, par: 3, score: 3, putts: 1, gir: false, girMiss: "left", fairway: null, penalties: 0 },
      { hole: 15, yards: 288, strokeIndex: 18, par: 4, score: 5, putts: 2, gir: false, girMiss: "short", fairway: "right", penalties: 0 },
      { hole: 16, yards: 362, strokeIndex: 4, par: 4, score: 4, putts: 1, gir: false, girMiss: "short", fairway: "right", penalties: 0 },
      { hole: 17, yards: 131, strokeIndex: 16, par: 3, score: 3, putts: 2, gir: true, girMiss: null, fairway: null, penalties: 0 },
      { hole: 18, yards: 331, strokeIndex: 8, par: 4, score: 6, putts: 3, gir: false, girMiss: "short", fairway: "left", penalties: 0 },
    ],
  },
  {
    id: "ghin-2026-03-29-84h",
    label: "R5 – 18",
    date: "03/29/2026",
    course: "Wenatchee Golf & Country Club",
    tees: "Black/Blue",
    mode: "advanced",
    source: "ghin-screenshot",
    postedType: "H",
    crSlope: "70.3/133",
    pcc: "-",
    differential: 11.6,
    holes: [
      { hole: 1, yards: 537, strokeIndex: 13, par: 5, score: 5, putts: 1, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 2, yards: 149, strokeIndex: 17, par: 3, score: 4, putts: 2, gir: false, girMiss: "long", fairway: null, penalties: 0 },
      { hole: 3, yards: 389, strokeIndex: 3, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 4, yards: 356, strokeIndex: 15, par: 4, score: 4, putts: 1, gir: false, girMiss: "short", fairway: "left", penalties: 0 },
      { hole: 5, yards: 356, strokeIndex: 5, par: 4, score: 3, putts: 1, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 6, yards: 193, strokeIndex: 11, par: 3, score: 4, putts: 2, gir: false, girMiss: "left", fairway: null, penalties: 0 },
      { hole: 7, yards: 550, strokeIndex: 9, par: 5, score: 5, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 8, yards: 397, strokeIndex: 1, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 9, yards: 356, strokeIndex: 7, par: 4, score: 5, putts: 2, gir: false, girMiss: "right", fairway: "right", penalties: 0 },
      { hole: 10, yards: 460, strokeIndex: 12, par: 5, score: 6, putts: 3, gir: true, girMiss: null, fairway: "right", penalties: 0 },
      { hole: 11, yards: 425, strokeIndex: 2, par: 4, score: 6, putts: 4, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 12, yards: 296, strokeIndex: 14, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "left", penalties: 0 },
      { hole: 13, yards: 498, strokeIndex: 10, par: 5, score: 4, putts: 1, gir: true, girMiss: null, fairway: "right", penalties: 0 },
      { hole: 14, yards: 163, strokeIndex: 6, par: 3, score: 5, putts: 2, gir: false, girMiss: "short", fairway: null, penalties: 0 },
      { hole: 15, yards: 288, strokeIndex: 18, par: 4, score: 5, putts: 2, gir: false, girMiss: "right", fairway: "right", penalties: 0 },
      { hole: 16, yards: 362, strokeIndex: 4, par: 4, score: 6, putts: 2, gir: false, girMiss: "left", fairway: "left", penalties: 0 },
      { hole: 17, yards: 131, strokeIndex: 16, par: 3, score: 4, putts: 2, gir: false, girMiss: "right", fairway: null, penalties: 0 },
      { hole: 18, yards: 331, strokeIndex: 8, par: 4, score: 6, putts: 2, gir: false, girMiss: "long", fairway: "hit", penalties: 0 },
    ],
  },
  {
    id: "ghin-2026-03-30-81h",
    label: "R6 - 18",
    date: "03/30/2026",
    course: "Wenatchee Golf & Country Club",
    tees: "Black/Blue",
    mode: "advanced",
    source: "ghin-screenshot",
    postedType: "H",
    crSlope: "69.7/130",
    pcc: "-",
    differential: 9.8,
    adjustedScore: 81,
    holes: [
      { hole: 1, yards: 527, strokeIndex: 13, par: 5, score: 5, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 2, yards: 147, strokeIndex: 17, par: 3, score: 4, putts: 2, gir: false, girMiss: "short", fairway: null, penalties: 0 },
      { hole: 3, yards: 389, strokeIndex: 3, par: 4, score: 5, putts: 2, gir: false, girMiss: "right", fairway: "left", penalties: 0 },
      { hole: 4, yards: 331, strokeIndex: 15, par: 4, score: 5, putts: 2, gir: false, girMiss: "long", fairway: "right", penalties: 0 },
      { hole: 5, yards: 356, strokeIndex: 5, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 6, yards: 193, strokeIndex: 11, par: 3, score: 3, putts: 1, gir: false, girMiss: "left", fairway: null, penalties: 0 },
      { hole: 7, yards: 550, strokeIndex: 9, par: 5, score: 6, putts: 2, gir: false, girMiss: "long", fairway: "hit", penalties: 0 },
      { hole: 8, yards: 353, strokeIndex: 1, par: 4, score: 5, putts: 2, gir: false, girMiss: "short", fairway: "hit", penalties: 0 },
      { hole: 9, yards: 347, strokeIndex: 7, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "right", penalties: 0 },
      { hole: 10, yards: 460, strokeIndex: 12, par: 5, score: 5, putts: 2, gir: true, girMiss: null, fairway: "right", penalties: 0 },
      { hole: 11, yards: 425, strokeIndex: 2, par: 4, score: 4, putts: 1, gir: false, girMiss: "short", fairway: "hit", penalties: 0 },
      { hole: 12, yards: 281, strokeIndex: 14, par: 4, score: 4, putts: 1, gir: false, girMiss: "short", fairway: "right", penalties: 0 },
      { hole: 13, yards: 482, strokeIndex: 10, par: 5, score: 6, putts: 2, gir: false, girMiss: "long", fairway: "left", penalties: 0 },
      { hole: 14, yards: 163, strokeIndex: 6, par: 3, score: 4, putts: 2, gir: false, girMiss: "left", fairway: null, penalties: 0 },
      { hole: 15, yards: 279, strokeIndex: 18, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "right", penalties: 0 },
      { hole: 16, yards: 362, strokeIndex: 4, par: 4, score: 7, putts: 2, gir: false, girMiss: "short", fairway: "left", penalties: 0 },
      { hole: 17, yards: 122, strokeIndex: 16, par: 3, score: 3, putts: 1, gir: false, girMiss: "right", fairway: null, penalties: 0 },
      { hole: 18, yards: 322, strokeIndex: 8, par: 4, score: 4, putts: 1, gir: false, girMiss: "left", fairway: "hit", penalties: 0 },
    ],
  },
  {
    id: "ghin-2026-03-31-82h",
    label: "R7 - 18",
    date: "03/31/2026",
    course: "Wenatchee Golf & Country Club",
    tees: "Black/Blue",
    mode: "advanced",
    source: "ghin-screenshot",
    postedType: "H",
    crSlope: "70.3/133",
    pcc: "-",
    differential: 9.9,
    holes: [
      { hole: 1, yards: 537, strokeIndex: 13, par: 5, score: 5, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 2, yards: 149, strokeIndex: 17, par: 3, score: 5, putts: 2, gir: false, girMiss: "short", fairway: null, penalties: 0 },
      { hole: 3, yards: 389, strokeIndex: 3, par: 4, score: 4, putts: 1, gir: false, girMiss: "short", fairway: "hit", penalties: 0 },
      { hole: 4, yards: 356, strokeIndex: 15, par: 4, score: 5, putts: 2, gir: false, girMiss: "long", fairway: "left", penalties: 0 },
      { hole: 5, yards: 356, strokeIndex: 5, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 6, yards: 193, strokeIndex: 11, par: 3, score: 3, putts: 2, gir: true, girMiss: null, fairway: null, penalties: 0 },
      { hole: 7, yards: 550, strokeIndex: 9, par: 5, score: 5, putts: 2, gir: true, girMiss: null, fairway: "right", penalties: 0 },
      { hole: 8, yards: 397, strokeIndex: 1, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 9, yards: 356, strokeIndex: 7, par: 4, score: 4, putts: 1, gir: false, girMiss: "left", fairway: "hit", penalties: 0 },
      { hole: 10, yards: 460, strokeIndex: 12, par: 5, score: 5, putts: 2, gir: true, girMiss: null, fairway: "left", penalties: 0 },
      { hole: 11, yards: 425, strokeIndex: 2, par: 4, score: 5, putts: 2, gir: false, girMiss: "right", fairway: "left", penalties: 0 },
      { hole: 12, yards: 296, strokeIndex: 14, par: 4, score: 5, putts: 3, gir: true, girMiss: null, fairway: "right", penalties: 0 },
      { hole: 13, yards: 498, strokeIndex: 10, par: 5, score: 5, putts: 2, gir: true, girMiss: null, fairway: "short", penalties: 0 },
      { hole: 14, yards: 163, strokeIndex: 6, par: 3, score: 3, putts: 1, gir: false, girMiss: "short", fairway: null, penalties: 0 },
      { hole: 15, yards: 288, strokeIndex: 18, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "right", penalties: 0 },
      { hole: 16, yards: 362, strokeIndex: 4, par: 4, score: 6, putts: 2, gir: false, girMiss: "long", fairway: "right", penalties: 0 },
      { hole: 17, yards: 131, strokeIndex: 16, par: 3, score: 4, putts: 3, gir: true, girMiss: null, fairway: null, penalties: 0 },
      { hole: 18, yards: 331, strokeIndex: 8, par: 4, score: 6, putts: 2, gir: false, girMiss: "right", fairway: "right", penalties: 0 },
    ],
  },
  {
    id: "ghin-2026-04-04-82h",
    label: "R8 - 18",
    date: "04/04/2026",
    course: "Wenatchee Golf & Country Club",
    tees: "Black/Blue",
    mode: "advanced",
    source: "ghin-screenshot",
    postedType: "H",
    crSlope: "70.3/133",
    pcc: "-",
    differential: 9.9,
    holes: [
      { hole: 1, yards: 537, strokeIndex: 13, par: 5, score: 5, putts: 1, gir: false, girMiss: "left", fairway: "hit", penalties: 0 },
      { hole: 2, yards: 149, strokeIndex: 17, par: 3, score: 3, putts: 1, gir: false, girMiss: "short", fairway: null, penalties: 0 },
      { hole: 3, yards: 389, strokeIndex: 3, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "right", penalties: 0 },
      { hole: 4, yards: 356, strokeIndex: 15, par: 4, score: 5, putts: 2, gir: false, girMiss: "long", fairway: "right", penalties: 0 },
      { hole: 5, yards: 356, strokeIndex: 5, par: 4, score: 5, putts: 1, gir: false, girMiss: "short", fairway: "left", penalties: 0 },
      { hole: 6, yards: 193, strokeIndex: 11, par: 3, score: 3, putts: 1, gir: false, girMiss: "short", fairway: null, penalties: 0 },
      { hole: 7, yards: 550, strokeIndex: 9, par: 5, score: 6, putts: 1, gir: false, girMiss: "right", fairway: "left", penalties: 0 },
      { hole: 8, yards: 397, strokeIndex: 1, par: 4, score: 6, putts: 2, gir: false, girMiss: "right", fairway: "left", penalties: 0 },
      { hole: 9, yards: 356, strokeIndex: 7, par: 4, score: 5, putts: 2, gir: false, girMiss: "short", fairway: "right", penalties: 0 },
      { hole: 10, yards: 460, strokeIndex: 12, par: 5, score: 6, putts: 2, gir: false, girMiss: "short", fairway: "right", penalties: 0 },
      { hole: 11, yards: 425, strokeIndex: 2, par: 4, score: 5, putts: 2, gir: false, girMiss: "short", fairway: "left", penalties: 0 },
      { hole: 12, yards: 296, strokeIndex: 14, par: 4, score: 5, putts: 2, gir: false, girMiss: "short", fairway: "hit", penalties: 0 },
      { hole: 13, yards: 498, strokeIndex: 10, par: 5, score: 4, putts: 1, gir: true, girMiss: null, fairway: "right", penalties: 0 },
      { hole: 14, yards: 163, strokeIndex: 6, par: 3, score: 4, putts: 2, gir: false, girMiss: "short", fairway: null, penalties: 0 },
      { hole: 15, yards: 288, strokeIndex: 18, par: 4, score: 4, putts: 1, gir: false, girMiss: "right", fairway: "left", penalties: 0 },
      { hole: 16, yards: 362, strokeIndex: 4, par: 4, score: 5, putts: 2, gir: false, girMiss: "short", fairway: "right", penalties: 0 },
      { hole: 17, yards: 131, strokeIndex: 16, par: 3, score: 3, putts: 2, gir: true, girMiss: null, fairway: null, penalties: 0 },
      { hole: 18, yards: 331, strokeIndex: 8, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "left", penalties: 0 },
    ],
  },
  {
    id: "ghin-2026-04-05-82h",
    label: "R9 - 18",
    date: "04/05/2026",
    course: "Wenatchee Golf & Country Club",
    tees: "Black/Blue",
    mode: "advanced",
    source: "ghin-screenshot",
    postedType: "H",
    crSlope: "70.3/133",
    pcc: "-",
    differential: 9.9,
    holes: [
      { hole: 1, yards: 537, strokeIndex: 13, par: 5, score: 6, putts: 1, gir: false, girMiss: "right", fairway: "right", penalties: 0 },
      { hole: 2, yards: 149, strokeIndex: 17, par: 3, score: 3, putts: 2, gir: true, girMiss: null, fairway: null, penalties: 0 },
      { hole: 3, yards: 389, strokeIndex: 3, par: 4, score: 7, putts: 2, gir: false, girMiss: "left", fairway: "hit", penalties: 0 },
      { hole: 4, yards: 356, strokeIndex: 15, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 5, yards: 356, strokeIndex: 5, par: 4, score: 5, putts: 2, gir: false, girMiss: "short", fairway: "right", penalties: 0 },
      { hole: 6, yards: 193, strokeIndex: 11, par: 3, score: 4, putts: 2, gir: false, girMiss: "left", fairway: null, penalties: 0 },
      { hole: 7, yards: 550, strokeIndex: 9, par: 5, score: 6, putts: 2, gir: false, girMiss: "long", fairway: "right", penalties: 0 },
      { hole: 8, yards: 397, strokeIndex: 1, par: 4, score: 4, putts: 1, gir: false, girMiss: "short", fairway: "left", penalties: 0 },
      { hole: 9, yards: 356, strokeIndex: 7, par: 4, score: 4, putts: 1, gir: false, girMiss: "short", fairway: "left", penalties: 0 },
      { hole: 10, yards: 460, strokeIndex: 12, par: 5, score: 5, putts: 2, gir: true, girMiss: null, fairway: "right", penalties: 0 },
      { hole: 11, yards: 425, strokeIndex: 2, par: 4, score: 5, putts: 1, gir: false, girMiss: "short", fairway: "right", penalties: 0 },
      { hole: 12, yards: 296, strokeIndex: 14, par: 4, score: 6, putts: 2, gir: false, girMiss: "short", fairway: "left", penalties: 0 },
      { hole: 13, yards: 498, strokeIndex: 10, par: 5, score: 6, putts: 2, gir: false, girMiss: "short", fairway: "right", penalties: 0 },
      { hole: 14, yards: 163, strokeIndex: 6, par: 3, score: 3, putts: 2, gir: true, girMiss: null, fairway: null, penalties: 0 },
      { hole: 15, yards: 288, strokeIndex: 18, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "left", penalties: 0 },
      { hole: 16, yards: 362, strokeIndex: 4, par: 4, score: 3, putts: 1, gir: true, girMiss: null, fairway: "right", penalties: 0 },
      { hole: 17, yards: 131, strokeIndex: 16, par: 3, score: 3, putts: 2, gir: true, girMiss: null, fairway: null, penalties: 0 },
      { hole: 18, yards: 331, strokeIndex: 8, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
    ],
  },
  {
    id: "ghin-2026-04-09-44n",
    label: "R10 - F9",
    date: "04/09/2026",
    course: "Wenatchee Golf & Country Club",
    tees: "Black/Blue",
    mode: "advanced",
    source: "ghin-screenshot",
    postedType: "N",
    crSlope: "36.1/135",
    pcc: "-",
    differential: 10.8,
    holes: [
      { hole: 1, yards: 537, strokeIndex: 13, par: 5, score: 5, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 2, yards: 149, strokeIndex: 17, par: 3, score: 4, putts: 2, gir: false, girMiss: "right", fairway: null, penalties: 0 },
      { hole: 3, yards: 389, strokeIndex: 3, par: 4, score: 5, putts: 2, gir: false, girMiss: "right", fairway: "left", penalties: 0 },
      { hole: 4, yards: 356, strokeIndex: 15, par: 4, score: 5, putts: 2, gir: false, girMiss: "long", fairway: "left", penalties: 0 },
      { hole: 5, yards: 356, strokeIndex: 5, par: 4, score: 6, putts: 3, gir: false, girMiss: "right", fairway: "left", penalties: 0 },
      { hole: 6, yards: 193, strokeIndex: 11, par: 3, score: 4, putts: 2, gir: false, girMiss: "left", fairway: null, penalties: 0 },
      { hole: 7, yards: 550, strokeIndex: 9, par: 5, score: 5, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 8, yards: 397, strokeIndex: 1, par: 4, score: 4, putts: 1, gir: false, girMiss: "left", fairway: "hit", penalties: 0 },
      { hole: 9, yards: 356, strokeIndex: 7, par: 4, score: 6, putts: 2, gir: false, girMiss: "short", fairway: "right", penalties: 0 },
    ],
  },
  {
    id: "ghin-2026-04-11-83h",
    label: "R11 - 18",
    date: "04/11/2026",
    course: "Wenatchee Golf & Country Club",
    tees: "Black/Blue",
    mode: "advanced",
    source: "ghin-screenshot",
    postedType: "H",
    crSlope: "70.3/133",
    pcc: "-",
    differential: 10.8,
    holes: [
      { hole: 1, yards: 537, strokeIndex: 13, par: 5, score: 5, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 2, yards: 149, strokeIndex: 17, par: 3, score: 4, putts: 2, gir: false, girMiss: "short", fairway: null, penalties: 0 },
      { hole: 3, yards: 389, strokeIndex: 3, par: 4, score: 4, putts: 3, gir: true, girMiss: null, fairway: "left", penalties: 0 },
      { hole: 4, yards: 356, strokeIndex: 15, par: 4, score: 5, putts: 2, gir: false, girMiss: "short", fairway: "left", penalties: 0 },
      { hole: 5, yards: 356, strokeIndex: 5, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "left", penalties: 0 },
      { hole: 6, yards: 193, strokeIndex: 11, par: 3, score: 3, putts: 1, gir: false, girMiss: "left", fairway: null, penalties: 0 },
      { hole: 7, yards: 550, strokeIndex: 9, par: 5, score: 6, putts: 2, gir: false, girMiss: "short", fairway: "left", penalties: 0 },
      { hole: 8, yards: 397, strokeIndex: 1, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 9, yards: 356, strokeIndex: 7, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 10, yards: 460, strokeIndex: 12, par: 5, score: 7, putts: 2, gir: false, girMiss: "long", fairway: "left", penalties: 0 },
      { hole: 11, yards: 425, strokeIndex: 2, par: 4, score: 5, putts: 2, gir: false, girMiss: "short", fairway: "right", penalties: 0 },
      { hole: 12, yards: 296, strokeIndex: 14, par: 4, score: 6, putts: 3, gir: false, girMiss: "left", fairway: "hit", penalties: 0 },
      { hole: 13, yards: 498, strokeIndex: 10, par: 5, score: 6, putts: 2, gir: false, girMiss: "short", fairway: "right", penalties: 0 },
      { hole: 14, yards: 163, strokeIndex: 6, par: 3, score: 3, putts: 2, gir: true, girMiss: null, fairway: null, penalties: 0 },
      { hole: 15, yards: 288, strokeIndex: 18, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 16, yards: 362, strokeIndex: 4, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 17, yards: 131, strokeIndex: 16, par: 3, score: 4, putts: 3, gir: true, girMiss: null, fairway: null, penalties: 0 },
      { hole: 18, yards: 331, strokeIndex: 8, par: 4, score: 5, putts: 2, gir: false, girMiss: "short", fairway: "left", penalties: 0 },
    ],
  },
  {
    id: "ghin-2026-04-12-81h",
    label: "R12 - 18",
    date: "04/12/2026",
    course: "Wenatchee Golf & Country Club",
    tees: "Black/Blue",
    mode: "advanced",
    source: "ghin-screenshot",
    postedType: "H",
    crSlope: "70.3/133",
    pcc: "-",
    differential: 9.1,
    holes: [
      { hole: 1, yards: 537, strokeIndex: 13, par: 5, score: 5, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 2, yards: 149, strokeIndex: 17, par: 3, score: 2, putts: 1, gir: true, girMiss: null, fairway: null, penalties: 0 },
      { hole: 3, yards: 389, strokeIndex: 3, par: 4, score: 5, putts: 1, gir: false, girMiss: "left", fairway: "right", penalties: 0 },
      { hole: 4, yards: 356, strokeIndex: 15, par: 4, score: 5, putts: 2, gir: false, girMiss: "left", fairway: "right", penalties: 0 },
      { hole: 5, yards: 356, strokeIndex: 5, par: 4, score: 5, putts: 2, gir: false, girMiss: "long", fairway: "hit", penalties: 0 },
      { hole: 6, yards: 193, strokeIndex: 11, par: 3, score: 4, putts: 2, gir: false, girMiss: "left", fairway: null, penalties: 0 },
      { hole: 7, yards: 550, strokeIndex: 9, par: 5, score: 6, putts: 1, gir: false, girMiss: "long", fairway: "hit", penalties: 0 },
      { hole: 8, yards: 397, strokeIndex: 1, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "left", penalties: 0 },
      { hole: 9, yards: 356, strokeIndex: 7, par: 4, score: 3, putts: 1, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 10, yards: 460, strokeIndex: 12, par: 5, score: 5, putts: 2, gir: true, girMiss: null, fairway: "right", penalties: 0 },
      { hole: 11, yards: 425, strokeIndex: 2, par: 4, score: 4, putts: 1, gir: false, girMiss: "long", fairway: "left", penalties: 0 },
      { hole: 12, yards: 296, strokeIndex: 14, par: 4, score: 6, putts: 3, gir: false, girMiss: "left", fairway: "left", penalties: 0 },
      { hole: 13, yards: 498, strokeIndex: 10, par: 5, score: 5, putts: 1, gir: false, girMiss: "short", fairway: "hit", penalties: 0 },
      { hole: 14, yards: 163, strokeIndex: 6, par: 3, score: 3, putts: 1, gir: false, girMiss: "right", fairway: null, penalties: 0 },
      { hole: 15, yards: 288, strokeIndex: 18, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 16, yards: 362, strokeIndex: 4, par: 4, score: 4, putts: 1, gir: false, girMiss: "long", fairway: "hit", penalties: 0 },
      { hole: 17, yards: 131, strokeIndex: 16, par: 3, score: 5, putts: 2, gir: false, girMiss: "short", fairway: null, penalties: 0 },
      { hole: 18, yards: 331, strokeIndex: 8, par: 4, score: 6, putts: 2, gir: false, girMiss: "short", fairway: "left", penalties: 0 },
    ],
  },
  {
    id: "ghin-2026-04-13-86a",
    label: "R13 - 18",
    date: "04/13/2026",
    course: "Rock Island Golf Course",
    tees: "Standard",
    mode: "advanced",
    source: "ghin-screenshot",
    postedType: "A",
    crSlope: "71.6/124",
    pcc: "-",
    differential: 13.1,
    holes: [
      { hole: 1, yards: 348, strokeIndex: 9, par: 4, score: 5, putts: 1, gir: false, girMiss: "long", fairway: "left", penalties: 0 },
      { hole: 2, yards: 426, strokeIndex: 5, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "right", penalties: 0 },
      { hole: 3, yards: 160, strokeIndex: 17, par: 3, score: 3, putts: 1, gir: false, girMiss: "long", fairway: null, penalties: 0 },
      { hole: 4, yards: 407, strokeIndex: 15, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "left", penalties: 0 },
      { hole: 5, yards: 570, strokeIndex: 7, par: 5, score: 7, putts: 2, gir: false, girMiss: "short", fairway: "right", penalties: 0 },
      { hole: 6, yards: 403, strokeIndex: 3, par: 4, score: 5, putts: 2, gir: false, girMiss: "short", fairway: "right", penalties: 0 },
      { hole: 7, yards: 195, strokeIndex: 13, par: 3, score: 4, putts: 3, gir: true, girMiss: null, fairway: null, penalties: 0 },
      { hole: 8, yards: 532, strokeIndex: 1, par: 5, score: 7, putts: 2, gir: false, girMiss: "short", fairway: "right", penalties: 0 },
      { hole: 9, yards: 312, strokeIndex: 11, par: 4, score: 5, putts: 2, gir: false, girMiss: "long", fairway: "hit", penalties: 0 },
      { hole: 10, yards: 380, strokeIndex: 4, par: 4, score: 6, putts: 1, gir: false, girMiss: "left", fairway: "left", penalties: 0 },
      { hole: 11, yards: 320, strokeIndex: 14, par: 4, score: 3, putts: 1, gir: true, girMiss: null, fairway: "right", penalties: 0 },
      { hole: 12, yards: 544, strokeIndex: 2, par: 5, score: 7, putts: 3, gir: false, girMiss: "left", fairway: "hit", penalties: 0 },
      { hole: 13, yards: 357, strokeIndex: 12, par: 4, score: 5, putts: 2, gir: false, girMiss: "short", fairway: "hit", penalties: 0 },
      { hole: 14, yards: 187, strokeIndex: 16, par: 3, score: 4, putts: 2, gir: false, girMiss: "left", fairway: null, penalties: 0 },
      { hole: 15, yards: 491, strokeIndex: 8, par: 5, score: 6, putts: 2, gir: false, girMiss: "long", fairway: "hit", penalties: 0 },
      { hole: 16, yards: 418, strokeIndex: 6, par: 4, score: 3, putts: 0, gir: false, girMiss: "left", fairway: "hit", penalties: 0 },
      { hole: 17, yards: 411, strokeIndex: 10, par: 4, score: 5, putts: 2, gir: false, girMiss: "right", fairway: "hit", penalties: 0 },
      { hole: 18, yards: 176, strokeIndex: 18, par: 3, score: 3, putts: 1, gir: false, girMiss: "long", fairway: null, penalties: 0 },
    ],
  },
  {
    id: "ghin-2026-04-21-87h",
    label: "R14 - 18",
    date: "04/21/2026",
    course: "Wenatchee Golf & Country Club",
    tees: "Black/Blue",
    mode: "advanced",
    source: "ghin-screenshot",
    postedType: "H",
    crSlope: "70.3/133",
    pcc: "-",
    differential: 14.2,
    holes: [
      { hole: 1, yards: 537, strokeIndex: 13, par: 5, score: 5, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 2, yards: 149, strokeIndex: 17, par: 3, score: 4, putts: 2, gir: false, girMiss: "right", fairway: null, penalties: 0 },
      { hole: 3, yards: 389, strokeIndex: 3, par: 4, score: 5, putts: 2, gir: false, girMiss: "short", fairway: "left", penalties: 0 },
      { hole: 4, yards: 356, strokeIndex: 15, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "right", penalties: 0 },
      { hole: 5, yards: 356, strokeIndex: 5, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 6, yards: 193, strokeIndex: 11, par: 3, score: 4, putts: 2, gir: false, girMiss: "short", fairway: null, penalties: 0 },
      { hole: 7, yards: 550, strokeIndex: 9, par: 5, score: 6, putts: 2, gir: false, girMiss: "short", fairway: "right", penalties: 0 },
      { hole: 8, yards: 397, strokeIndex: 1, par: 4, score: 5, putts: 2, gir: false, girMiss: "right", fairway: "right", penalties: 0 },
      { hole: 9, yards: 356, strokeIndex: 7, par: 4, score: 5, putts: 2, gir: false, girMiss: "short", fairway: "right", penalties: 0 },
      { hole: 10, yards: 460, strokeIndex: 12, par: 5, score: 6, putts: 3, gir: true, girMiss: null, fairway: "right", penalties: 0 },
      { hole: 11, yards: 425, strokeIndex: 2, par: 4, score: 6, putts: 2, gir: false, girMiss: "short", fairway: "left", penalties: 0 },
      { hole: 12, yards: 296, strokeIndex: 14, par: 4, score: 5, putts: 1, gir: false, girMiss: "long", fairway: "hit", penalties: 0 },
      { hole: 13, yards: 498, strokeIndex: 10, par: 5, score: 7, putts: 3, gir: false, girMiss: "short", fairway: "left", penalties: 0 },
      { hole: 14, yards: 163, strokeIndex: 6, par: 3, score: 3, putts: 2, gir: true, girMiss: null, fairway: null, penalties: 0 },
      { hole: 15, yards: 288, strokeIndex: 18, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 16, yards: 362, strokeIndex: 4, par: 4, score: 4, putts: 1, gir: false, girMiss: "short", fairway: "hit", penalties: 0 },
      { hole: 17, yards: 131, strokeIndex: 16, par: 3, score: 5, putts: 1, gir: false, girMiss: "left", fairway: null, penalties: 0 },
      { hole: 18, yards: 331, strokeIndex: 8, par: 4, score: 5, putts: 3, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
    ],
  },
  {
    id: "ghin-2026-04-30-43n",
    label: "R15 - F9",
    date: "04/30/2026",
    course: "Wenatchee Golf & Country Club",
    tees: "Blue/White",
    mode: "advanced",
    source: "ghin-screenshot",
    postedType: "N",
    crSlope: "36.6/136",
    pcc: "-",
    differential: 10.3,
    holes: [
      { hole: 1, yards: 537, strokeIndex: 13, par: 5, score: 4, putts: 1, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 2, yards: 149, strokeIndex: 17, par: 3, score: 3, putts: 1, gir: false, girMiss: "short", fairway: null, penalties: 0 },
      { hole: 3, yards: 398, strokeIndex: 3, par: 4, score: 6, putts: 1, gir: false, girMiss: "short", fairway: "left", penalties: 0 },
      { hole: 4, yards: 356, strokeIndex: 15, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 5, yards: 376, strokeIndex: 5, par: 4, score: 6, putts: 2, gir: false, girMiss: "right", fairway: "right", penalties: 0 },
      { hole: 6, yards: 218, strokeIndex: 11, par: 3, score: 3, putts: 2, gir: true, girMiss: null, fairway: null, penalties: 0 },
      { hole: 7, yards: 582, strokeIndex: 9, par: 5, score: 7, putts: 2, gir: false, girMiss: "right", fairway: "right", penalties: 0 },
      { hole: 8, yards: 397, strokeIndex: 1, par: 4, score: 5, putts: 2, gir: false, girMiss: "short", fairway: "short", penalties: 0 },
      { hole: 9, yards: 356, strokeIndex: 7, par: 4, score: 5, putts: 2, gir: false, girMiss: "long", fairway: "hit", penalties: 0 },
    ],
  },
  {
    id: "ghin-2026-05-02-72a",
    label: "R16 - 18",
    date: "05/02/2026",
    course: "Palouse Ridge Golf Club",
    tees: "Grey/Blue Combo",
    mode: "advanced",
    source: "ghin-screenshot",
    postedType: "A",
    crSlope: "71.2/133",
    pcc: "-1",
    differential: 1.5,
    holes: [
      { hole: 1, yards: 378, strokeIndex: 3, par: 4, score: 4, putts: 1, gir: false, girMiss: "long", fairway: "left", penalties: 0 },
      { hole: 2, yards: 369, strokeIndex: 17, par: 4, score: 5, putts: 1, gir: false, girMiss: "long", fairway: "left", penalties: 0 },
      { hole: 3, yards: 414, strokeIndex: 5, par: 4, score: 5, putts: 3, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 4, yards: 159, strokeIndex: 9, par: 3, score: 3, putts: 1, gir: false, girMiss: "long", fairway: null, penalties: 0 },
      { hole: 5, yards: 536, strokeIndex: 1, par: 5, score: 4, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 6, yards: 216, strokeIndex: 7, par: 3, score: 3, putts: 1, gir: false, girMiss: "right", fairway: null, penalties: 0 },
      { hole: 7, yards: 355, strokeIndex: 15, par: 4, score: 4, putts: 1, gir: false, girMiss: "right", fairway: "left", penalties: 0 },
      { hole: 8, yards: 380, strokeIndex: 11, par: 4, score: 3, putts: 1, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 9, yards: 485, strokeIndex: 13, par: 5, score: 5, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 10, yards: 574, strokeIndex: 8, par: 5, score: 5, putts: 2, gir: true, girMiss: null, fairway: "left", penalties: 0 },
      { hole: 11, yards: 156, strokeIndex: 10, par: 3, score: 2, putts: 1, gir: true, girMiss: null, fairway: null, penalties: 0 },
      { hole: 12, yards: 386, strokeIndex: 4, par: 4, score: 5, putts: 2, gir: false, girMiss: "left", fairway: "hit", penalties: 0 },
      { hole: 13, yards: 181, strokeIndex: 2, par: 3, score: 3, putts: 1, gir: false, girMiss: "long", fairway: null, penalties: 0 },
      { hole: 14, yards: 399, strokeIndex: 14, par: 4, score: 3, putts: 1, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 15, yards: 306, strokeIndex: 18, par: 4, score: 3, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 16, yards: 118, strokeIndex: 16, par: 3, score: 3, putts: 2, gir: true, girMiss: null, fairway: null, penalties: 0 },
      { hole: 17, yards: 508, strokeIndex: 12, par: 5, score: 5, putts: 3, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 18, yards: 492, strokeIndex: 6, par: 5, score: 7, putts: 2, gir: false, girMiss: "short", fairway: "hit", penalties: 0 },
    ],
  },
  {
    id: "ghin-2026-05-07-41n",
    label: "R17 - F9",
    date: "05/07/2026",
    course: "Wenatchee Golf & Country Club",
    tees: "Blue/White",
    mode: "advanced",
    source: "ghin-screenshot",
    postedType: "N",
    crSlope: "36.6/136",
    pcc: "-",
    differential: 8.4,
    holes: [
      { hole: 1, yards: 537, strokeIndex: 13, par: 5, score: 6, putts: 2, gir: false, girMiss: "left", fairway: "left", penalties: 0 },
      { hole: 2, yards: 149, strokeIndex: 17, par: 3, score: 3, putts: 1, gir: false, girMiss: "left", fairway: null, penalties: 0 },
      { hole: 3, yards: 398, strokeIndex: 3, par: 4, score: 6, putts: 2, gir: false, girMiss: "short", fairway: "left", penalties: 0 },
      { hole: 4, yards: 356, strokeIndex: 15, par: 4, score: 4, putts: 1, gir: false, girMiss: "left", fairway: "left", penalties: 0 },
      { hole: 5, yards: 376, strokeIndex: 5, par: 4, score: 5, putts: 2, gir: false, girMiss: "long", fairway: "left", penalties: 0 },
      { hole: 6, yards: 218, strokeIndex: 11, par: 3, score: 3, putts: 1, gir: false, girMiss: "right", fairway: null, penalties: 0 },
      { hole: 7, yards: 582, strokeIndex: 9, par: 5, score: 5, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 8, yards: 397, strokeIndex: 1, par: 4, score: 5, putts: 2, gir: false, girMiss: "short", fairway: "left", penalties: 0 },
      { hole: 9, yards: 356, strokeIndex: 7, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "right", penalties: 0 },
    ],
  },
  {
    id: "ghin-2026-05-09-78a",
    label: "R18 - 18",
    date: "05/09/2026",
    course: "Rock Island Golf Course",
    tees: "Standard",
    mode: "advanced",
    source: "ghin-screenshot",
    postedType: "A",
    crSlope: "71.6/124",
    pcc: "-",
    differential: 5.8,
    holes: [
      { hole: 1, yards: 348, strokeIndex: 9, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "right", penalties: 0 },
      { hole: 2, yards: 426, strokeIndex: 5, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 3, yards: 160, strokeIndex: 17, par: 3, score: 2, putts: 1, gir: true, girMiss: null, fairway: null, penalties: 0 },
      { hole: 4, yards: 407, strokeIndex: 15, par: 4, score: 5, putts: 3, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 5, yards: 570, strokeIndex: 7, par: 5, score: 7, putts: 2, gir: false, girMiss: "short", fairway: "left", penalties: 0 },
      { hole: 6, yards: 403, strokeIndex: 3, par: 4, score: 4, putts: 1, gir: false, girMiss: "left", fairway: "hit", penalties: 0 },
      { hole: 7, yards: 195, strokeIndex: 13, par: 3, score: 3, putts: 2, gir: true, girMiss: null, fairway: null, penalties: 0 },
      { hole: 8, yards: 532, strokeIndex: 1, par: 5, score: 5, putts: 1, gir: false, girMiss: "short", fairway: "left", penalties: 0 },
      { hole: 9, yards: 312, strokeIndex: 11, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 10, yards: 380, strokeIndex: 4, par: 4, score: 5, putts: 1, gir: false, girMiss: "long", fairway: "hit", penalties: 0 },
      { hole: 11, yards: 320, strokeIndex: 14, par: 4, score: 4, putts: 1, gir: false, girMiss: "short", fairway: "right", penalties: 0 },
      { hole: 12, yards: 544, strokeIndex: 2, par: 5, score: 5, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 13, yards: 357, strokeIndex: 12, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 14, yards: 187, strokeIndex: 16, par: 3, score: 4, putts: 2, gir: false, girMiss: "left", fairway: null, penalties: 0 },
      { hole: 15, yards: 491, strokeIndex: 8, par: 5, score: 5, putts: 1, gir: false, girMiss: "long", fairway: "right", penalties: 0 },
      { hole: 16, yards: 418, strokeIndex: 6, par: 4, score: 4, putts: 1, gir: false, girMiss: "long", fairway: "hit", penalties: 0 },
      { hole: 17, yards: 411, strokeIndex: 10, par: 4, score: 5, putts: 2, gir: false, girMiss: "short", fairway: "right", penalties: 0 },
      { hole: 18, yards: 176, strokeIndex: 18, par: 3, score: 4, putts: 3, gir: true, girMiss: null, fairway: null, penalties: 0 },
    ],
  },
  {
    id: "ghin-2026-05-10-78h",
    label: "R19 - 18",
    date: "05/10/2026",
    course: "Wenatchee Golf & Country Club",
    tees: "Black/Blue",
    mode: "advanced",
    source: "ghin-screenshot",
    postedType: "H",
    crSlope: "70.3/133",
    pcc: "-",
    differential: 6.5,
    holes: [
      { hole: 1, yards: 537, strokeIndex: 13, par: 5, score: 5, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 2, yards: 149, strokeIndex: 17, par: 3, score: 5, putts: 3, gir: false, girMiss: "left", fairway: null, penalties: 0 },
      { hole: 3, yards: 389, strokeIndex: 3, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "right", penalties: 0 },
      { hole: 4, yards: 356, strokeIndex: 15, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 5, yards: 356, strokeIndex: 5, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 6, yards: 193, strokeIndex: 11, par: 3, score: 4, putts: 2, gir: false, girMiss: "left", fairway: null, penalties: 0 },
      { hole: 7, yards: 550, strokeIndex: 9, par: 5, score: 5, putts: 1, gir: false, girMiss: "short", fairway: "left", penalties: 0 },
      { hole: 8, yards: 397, strokeIndex: 1, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 9, yards: 356, strokeIndex: 7, par: 4, score: 5, putts: 3, gir: true, girMiss: null, fairway: "left", penalties: 0 },
      { hole: 10, yards: 460, strokeIndex: 12, par: 5, score: 5, putts: 1, gir: false, girMiss: "right", fairway: "left", penalties: 0 },
      { hole: 11, yards: 425, strokeIndex: 2, par: 4, score: 5, putts: 3, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 12, yards: 296, strokeIndex: 14, par: 4, score: 5, putts: 2, gir: false, girMiss: "left", fairway: "left", penalties: 0 },
      { hole: 13, yards: 498, strokeIndex: 10, par: 5, score: 7, putts: 3, gir: false, girMiss: "short", fairway: "left", penalties: 0 },
      { hole: 14, yards: 163, strokeIndex: 6, par: 3, score: 2, putts: 1, gir: true, girMiss: null, fairway: null, penalties: 0 },
      { hole: 15, yards: 288, strokeIndex: 18, par: 4, score: 3, putts: 1, gir: true, girMiss: null, fairway: "left", penalties: 0 },
      { hole: 16, yards: 362, strokeIndex: 4, par: 4, score: 4, putts: 1, gir: false, girMiss: "short", fairway: "right", penalties: 0 },
      { hole: 17, yards: 131, strokeIndex: 16, par: 3, score: 3, putts: 2, gir: true, girMiss: null, fairway: null, penalties: 0 },
      { hole: 18, yards: 331, strokeIndex: 8, par: 4, score: 4, putts: 1, gir: false, girMiss: "long", fairway: "right", penalties: 0 },
    ],
  },
  {
    id: "ghin-2026-05-11-78h",
    label: "R20 - 18",
    date: "05/11/2026",
    course: "Wenatchee Golf & Country Club",
    tees: "Black/Blue",
    mode: "advanced",
    source: "ghin-screenshot",
    postedType: "H",
    crSlope: "70.3/133",
    pcc: "-",
    differential: 6.5,
    holes: [
      { hole: 1, yards: 537, strokeIndex: 13, par: 5, score: 5, putts: 2, gir: true, girMiss: null, fairway: "left", penalties: 0 },
      { hole: 2, yards: 149, strokeIndex: 17, par: 3, score: 5, putts: 2, gir: false, girMiss: "short", fairway: null, penalties: 0 },
      { hole: 3, yards: 389, strokeIndex: 3, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 4, yards: 356, strokeIndex: 15, par: 4, score: 4, putts: 1, gir: false, girMiss: "long", fairway: "right", penalties: 0 },
      { hole: 5, yards: 356, strokeIndex: 5, par: 4, score: 5, putts: 2, gir: false, girMiss: "long", fairway: "hit", penalties: 0 },
      { hole: 6, yards: 193, strokeIndex: 11, par: 3, score: 4, putts: 2, gir: false, girMiss: "long", fairway: null, penalties: 0 },
      { hole: 7, yards: 550, strokeIndex: 9, par: 5, score: 5, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 8, yards: 397, strokeIndex: 1, par: 4, score: 4, putts: 1, gir: false, girMiss: "short", fairway: "hit", penalties: 0 },
      { hole: 9, yards: 356, strokeIndex: 7, par: 4, score: 3, putts: 1, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 10, yards: 460, strokeIndex: 12, par: 5, score: 4, putts: 1, gir: true, girMiss: null, fairway: "right", penalties: 0 },
      { hole: 11, yards: 425, strokeIndex: 2, par: 4, score: 5, putts: 2, gir: false, girMiss: "left", fairway: "hit", penalties: 0 },
      { hole: 12, yards: 296, strokeIndex: 14, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 13, yards: 498, strokeIndex: 10, par: 5, score: 5, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 14, yards: 163, strokeIndex: 6, par: 3, score: 3, putts: 1, gir: false, girMiss: "short", fairway: null, penalties: 0 },
      { hole: 15, yards: 288, strokeIndex: 18, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 16, yards: 362, strokeIndex: 4, par: 4, score: 4, putts: 1, gir: false, girMiss: "long", fairway: "right", penalties: 0 },
      { hole: 17, yards: 131, strokeIndex: 16, par: 3, score: 4, putts: 3, gir: true, girMiss: null, fairway: null, penalties: 0 },
      { hole: 18, yards: 331, strokeIndex: 8, par: 4, score: 6, putts: 1, gir: false, girMiss: "short", fairway: "left", penalties: 0 },
    ],
  },
  {
    id: "ghin-2026-05-12-36n",
    label: "R21 - F9",
    date: "05/12/2026",
    course: "Wenatchee Golf & Country Club",
    tees: "Black/Blue",
    mode: "advanced",
    source: "ghin-screenshot",
    postedType: "N",
    crSlope: "36.1/135",
    pcc: "-",
    differential: 4.7,
    holes: [
      { hole: 1, yards: 537, strokeIndex: 13, par: 5, score: 5, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 2, yards: 149, strokeIndex: 17, par: 3, score: 3, putts: 2, gir: true, girMiss: null, fairway: null, penalties: 0 },
      { hole: 3, yards: 389, strokeIndex: 3, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 4, yards: 356, strokeIndex: 15, par: 4, score: 3, putts: 1, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 5, yards: 356, strokeIndex: 5, par: 4, score: 4, putts: 1, gir: false, girMiss: "left", fairway: "right", penalties: 0 },
      { hole: 6, yards: 193, strokeIndex: 11, par: 3, score: 3, putts: 2, gir: true, girMiss: null, fairway: null, penalties: 0 },
      { hole: 7, yards: 550, strokeIndex: 9, par: 5, score: 5, putts: 2, gir: true, girMiss: null, fairway: "left", penalties: 0 },
      { hole: 8, yards: 397, strokeIndex: 1, par: 4, score: 3, putts: 1, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 9, yards: 356, strokeIndex: 7, par: 4, score: 6, putts: 3, gir: false, girMiss: "short", fairway: "left", penalties: 0 },
    ],
  },
  {
    id: "ghin-2026-05-15-85h",
    label: "R22 - 18",
    date: "05/15/2026",
    course: "Wenatchee Golf & Country Club",
    tees: "Blue",
    mode: "advanced",
    source: "ghin-screenshot",
    postedType: "H",
    crSlope: "69.7/130",
    pcc: "-",
    differential: 13.3,
    adjustedScore: 85,
    holes: [
      { hole: 1, yards: 527, strokeIndex: 13, par: 5, score: 5, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 2, yards: 147, strokeIndex: 17, par: 3, score: 4, putts: 2, gir: false, girMiss: "left", fairway: null, penalties: 0 },
      { hole: 3, yards: 389, strokeIndex: 3, par: 4, score: 6, putts: 3, gir: false, girMiss: "short", fairway: "hit", penalties: 0 },
      { hole: 4, yards: 331, strokeIndex: 15, par: 4, score: 4, putts: 1, gir: false, girMiss: "right", fairway: "left", penalties: 0 },
      { hole: 5, yards: 356, strokeIndex: 5, par: 4, score: 5, putts: 2, gir: false, girMiss: "long", fairway: "hit", penalties: 0 },
      { hole: 6, yards: 193, strokeIndex: 11, par: 3, score: 3, putts: 1, gir: false, girMiss: "short", fairway: null, penalties: 0 },
      { hole: 7, yards: 550, strokeIndex: 9, par: 5, score: 5, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 8, yards: 353, strokeIndex: 1, par: 4, score: 5, putts: 2, gir: true, girMiss: null, fairway: "left", penalties: 0 },
      { hole: 9, yards: 347, strokeIndex: 7, par: 4, score: 5, putts: 3, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 10, yards: 460, strokeIndex: 12, par: 5, score: 8, putts: 2, gir: false, girMiss: "left", fairway: "right", penalties: 0 },
      { hole: 11, yards: 425, strokeIndex: 2, par: 4, score: 5, putts: 3, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 12, yards: 281, strokeIndex: 14, par: 4, score: 6, putts: 2, gir: false, girMiss: "long", fairway: "right", penalties: 0 },
      { hole: 13, yards: 482, strokeIndex: 10, par: 5, score: 5, putts: 2, gir: true, girMiss: null, fairway: "right", penalties: 0 },
      { hole: 14, yards: 163, strokeIndex: 6, par: 3, score: 4, putts: 2, gir: false, girMiss: "long", fairway: null, penalties: 0 },
      { hole: 15, yards: 279, strokeIndex: 18, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 16, yards: 362, strokeIndex: 4, par: 4, score: 5, putts: 2, gir: false, girMiss: "short", fairway: "right", penalties: 0 },
      { hole: 17, yards: 122, strokeIndex: 16, par: 3, score: 3, putts: 2, gir: true, girMiss: null, fairway: null, penalties: 0 },
      { hole: 18, yards: 322, strokeIndex: 8, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
    ],
  },
  {
    id: "ghin-2026-05-17-84h-a",
    label: "R23 - 18",
    date: "05/17/2026",
    course: "Wenatchee Golf & Country Club",
    tees: "Black/Blue",
    mode: "advanced",
    source: "ghin-screenshot",
    postedType: "H",
    crSlope: "70.3/133",
    pcc: "-",
    differential: 11.6,
    adjustedScore: 84,
    holes: [
      { hole: 1, yards: 537, strokeIndex: 13, par: 5, score: 5, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 2, yards: 149, strokeIndex: 17, par: 3, score: 4, putts: 3, gir: true, girMiss: null, fairway: null, penalties: 0 },
      { hole: 3, yards: 389, strokeIndex: 3, par: 4, score: 4, putts: 1, gir: false, girMiss: "short", fairway: "hit", penalties: 0 },
      { hole: 4, yards: 356, strokeIndex: 15, par: 4, score: 5, putts: 3, gir: true, girMiss: null, fairway: "left", penalties: 0 },
      { hole: 5, yards: 356, strokeIndex: 5, par: 4, score: 5, putts: 2, gir: false, girMiss: "short", fairway: "left", penalties: 0 },
      { hole: 6, yards: 193, strokeIndex: 11, par: 3, score: 4, putts: 2, gir: false, girMiss: "right", fairway: null, penalties: 0 },
      { hole: 7, yards: 550, strokeIndex: 9, par: 5, score: 8, putts: 2, gir: false, girMiss: "left", fairway: "left", penalties: 0 },
      { hole: 8, yards: 397, strokeIndex: 1, par: 4, score: 6, putts: 2, gir: false, girMiss: "short", fairway: "left", penalties: 0 },
      { hole: 9, yards: 356, strokeIndex: 7, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 10, yards: 460, strokeIndex: 12, par: 5, score: 5, putts: 2, gir: true, girMiss: null, fairway: "right", penalties: 0 },
      { hole: 11, yards: 425, strokeIndex: 2, par: 4, score: 5, putts: 2, gir: false, girMiss: "short", fairway: "left", penalties: 0 },
      { hole: 12, yards: 296, strokeIndex: 14, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 13, yards: 498, strokeIndex: 10, par: 5, score: 6, putts: 3, gir: true, girMiss: null, fairway: "left", penalties: 0 },
      { hole: 14, yards: 163, strokeIndex: 6, par: 3, score: 5, putts: 1, gir: false, girMiss: "short", fairway: null, penalties: 0 },
      { hole: 15, yards: 288, strokeIndex: 18, par: 4, score: 4, putts: 1, gir: false, girMiss: "long", fairway: "right", penalties: 0 },
      { hole: 16, yards: 362, strokeIndex: 4, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 17, yards: 131, strokeIndex: 16, par: 3, score: 4, putts: 2, gir: false, girMiss: "right", fairway: null, penalties: 0 },
      { hole: 18, yards: 331, strokeIndex: 8, par: 4, score: 3, putts: 1, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
    ],
  },
  {
    id: "ghin-2026-05-17-84h-b",
    label: "R24 - 18",
    date: "05/17/2026",
    course: "Wenatchee Golf & Country Club",
    tees: "Black/Blue",
    mode: "advanced",
    source: "ghin-screenshot",
    postedType: "H",
    crSlope: "70.3/133",
    pcc: "-",
    differential: 11.6,
    holes: [
      { hole: 1, yards: 537, strokeIndex: 13, par: 5, score: 6, putts: 3, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 2, yards: 149, strokeIndex: 17, par: 3, score: 4, putts: 1, gir: false, girMiss: "short", fairway: null, penalties: 0 },
      { hole: 3, yards: 389, strokeIndex: 3, par: 4, score: 5, putts: 0, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 4, yards: 356, strokeIndex: 15, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 5, yards: 356, strokeIndex: 5, par: 4, score: 6, putts: 3, gir: false, girMiss: "short", fairway: "left", penalties: 0 },
      { hole: 6, yards: 193, strokeIndex: 11, par: 3, score: 4, putts: 2, gir: false, girMiss: "right", fairway: null, penalties: 0 },
      { hole: 7, yards: 550, strokeIndex: 9, par: 5, score: 6, putts: 2, gir: false, girMiss: "long", fairway: "hit", penalties: 0 },
      { hole: 8, yards: 397, strokeIndex: 1, par: 4, score: 3, putts: 1, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 9, yards: 356, strokeIndex: 7, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "left", penalties: 0 },
      { hole: 10, yards: 460, strokeIndex: 12, par: 5, score: 5, putts: 2, gir: false, girMiss: "short", fairway: "right", penalties: 0 },
      { hole: 11, yards: 425, strokeIndex: 2, par: 4, score: 4, putts: 2, gir: false, girMiss: "short", fairway: "right", penalties: 0 },
      { hole: 12, yards: 296, strokeIndex: 14, par: 4, score: 3, putts: 1, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 13, yards: 498, strokeIndex: 10, par: 5, score: 6, putts: 2, gir: false, girMiss: "short", fairway: "right", penalties: 0 },
      { hole: 14, yards: 163, strokeIndex: 6, par: 3, score: 6, putts: 2, gir: false, girMiss: "short", fairway: null, penalties: 0 },
      { hole: 15, yards: 288, strokeIndex: 18, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 16, yards: 362, strokeIndex: 4, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 17, yards: 131, strokeIndex: 16, par: 3, score: 4, putts: 3, gir: true, girMiss: null, fairway: null, penalties: 0 },
      { hole: 18, yards: 331, strokeIndex: 8, par: 4, score: 6, putts: 2, gir: false, girMiss: "short", fairway: "right", penalties: 0 },
    ],
  },
  {
    id: "ghin-2026-05-19-40n",
    label: "R25 - F9",
    date: "05/19/2026",
    course: "Wenatchee Golf & Country Club",
    tees: "Black/Blue",
    mode: "advanced",
    source: "ghin-screenshot",
    postedType: "N",
    crSlope: "36.1/135",
    pcc: "-",
    differential: 7.8,
    holes: [
      { hole: 1, yards: 537, strokeIndex: 13, par: 5, score: 4, putts: 1, gir: true, girMiss: null, fairway: "left", penalties: 0 },
      { hole: 2, yards: 149, strokeIndex: 17, par: 3, score: 5, putts: 1, gir: false, girMiss: "short", fairway: null, penalties: 0 },
      { hole: 3, yards: 389, strokeIndex: 3, par: 4, score: 5, putts: 3, gir: true, girMiss: null, fairway: "right", penalties: 0 },
      { hole: 4, yards: 356, strokeIndex: 15, par: 4, score: 5, putts: 2, gir: false, girMiss: "short", fairway: "left", penalties: 0 },
      { hole: 5, yards: 356, strokeIndex: 5, par: 4, score: 4, putts: 2, gir: true, girMiss: null, fairway: "hit", penalties: 0 },
      { hole: 6, yards: 193, strokeIndex: 11, par: 3, score: 4, putts: 1, gir: false, girMiss: "right", fairway: null, penalties: 0 },
      { hole: 7, yards: 550, strokeIndex: 9, par: 5, score: 5, putts: 2, gir: true, girMiss: null, fairway: "right", penalties: 0 },
      { hole: 8, yards: 397, strokeIndex: 1, par: 4, score: 5, putts: 2, gir: false, girMiss: "short", fairway: "left", penalties: 0 },
      { hole: 9, yards: 356, strokeIndex: 7, par: 4, score: 3, putts: 0, gir: false, girMiss: "short", fairway: "right", penalties: 0 },
    ],
  },
];
